const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

try {
  if (fs.existsSync(path.join(__dirname, 'convert-favicon.js'))) {
    execSync('node convert-favicon.js', { stdio: 'inherit' });
  }
} catch (error) {
  console.warn('Warning: Could not convert favicon to PNG:', error.message);
  console.warn('Continuing with build...');
}

let htmlContent = fs.readFileSync(path.join(__dirname, 'public', 'index.html'), 'utf8');
const jsContent = fs.readFileSync(path.join(__dirname, 'public', 'app.js'), 'utf8');
const faviconContent = fs.readFileSync(path.join(__dirname, 'public', 'favicon.svg'), 'utf8');
const appleTouchIconContent = fs.readFileSync(path.join(__dirname, 'public', 'apple-touch-icon.png'));
const svgHash = crypto.createHash('md5').update(faviconContent).digest('hex').substring(0, 8);
htmlContent = htmlContent.replace(
  /href="\/apple-touch-icon\.png"/,
  `href="/apple-touch-icon.png?v=${svgHash}`
);
const appleTouchIconBase64 = appleTouchIconContent.toString('base64');

const workerSecurity = fs.readFileSync(path.join(__dirname, 'worker-security.js'), 'utf8');
const workerRoutes = fs.readFileSync(path.join(__dirname, 'worker-routes.js'), 'utf8');

const workerContent = `// This file is auto-generated by build.js
const HTML_CONTENT = ${JSON.stringify(htmlContent)};
const JS_CONTENT = ${JSON.stringify(jsContent)};
const FAVICON_CONTENT = ${JSON.stringify(faviconContent)};
const APPLE_TOUCH_ICON_BASE64 = ${JSON.stringify(appleTouchIconBase64)};

${workerSecurity}
${workerRoutes}
`;

fs.writeFileSync(path.join(__dirname, 'src', 'index.js'), workerContent);
console.log('Build complete! Generated src/index.js');
