/* Auto-generated by ios/scripts/extract-logic.js — do not edit by hand. */

/*
 (c) 2011-2015, Vladimir Agafonkin
 SunCalc is a JavaScript library for calculating sun/moon position and light phases.
 https://github.com/mourner/suncalc
*/

(function () { 'use strict';

// shortcuts for easier to read formulas

var PI   = Math.PI,
    sin  = Math.sin,
    cos  = Math.cos,
    tan  = Math.tan,
    asin = Math.asin,
    atan = Math.atan2,
    acos = Math.acos,
    rad  = PI / 180;

// sun calculations are based on http://aa.quae.nl/en/reken/zonpositie.html formulas


// date/time constants and conversions

var dayMs = 1000 * 60 * 60 * 24,
    J1970 = 2440588,
    J2000 = 2451545;

function toJulian(date) { return date.valueOf() / dayMs - 0.5 + J1970; }
function fromJulian(j)  { return new Date((j + 0.5 - J1970) * dayMs); }
function toDays(date)   { return toJulian(date) - J2000; }


// general calculations for position

var e = rad * 23.4397; // obliquity of the Earth

function rightAscension(l, b) { return atan(sin(l) * cos(e) - tan(b) * sin(e), cos(l)); }
function declination(l, b)    { return asin(sin(b) * cos(e) + cos(b) * sin(e) * sin(l)); }

function azimuth(H, phi, dec)  { return atan(sin(H), cos(H) * sin(phi) - tan(dec) * cos(phi)); }
function altitude(H, phi, dec) { return asin(sin(phi) * sin(dec) + cos(phi) * cos(dec) * cos(H)); }

function siderealTime(d, lw) { return rad * (280.16 + 360.9856235 * d) - lw; }

function astroRefraction(h) {
    if (h < 0) // the following formula works for positive altitudes only.
        h = 0; // if h = -0.08901179 a div/0 would occur.

    // formula 16.4 of "Astronomical Algorithms" 2nd edition by Jean Meeus (Willmann-Bell, Richmond) 1998.
    // 1.02 / tan(h + 10.26 / (h + 5.10)) h in degrees, result in arc minutes -> converted to rad:
    return 0.0002967 / Math.tan(h + 0.00312536 / (h + 0.08901179));
}

// general sun calculations

function solarMeanAnomaly(d) { return rad * (357.5291 + 0.98560028 * d); }

function eclipticLongitude(M) {

    var C = rad * (1.9148 * sin(M) + 0.02 * sin(2 * M) + 0.0003 * sin(3 * M)), // equation of center
        P = rad * 102.9372; // perihelion of the Earth

    return M + C + P + PI;
}

function sunCoords(d) {

    var M = solarMeanAnomaly(d),
        L = eclipticLongitude(M);

    return {
        dec: declination(L, 0),
        ra: rightAscension(L, 0)
    };
}


var SunCalc = {};


// calculates sun position for a given date and latitude/longitude

SunCalc.getPosition = function (date, lat, lng) {

    var lw  = rad * -lng,
        phi = rad * lat,
        d   = toDays(date),

        c  = sunCoords(d),
        H  = siderealTime(d, lw) - c.ra;

    return {
        azimuth: azimuth(H, phi, c.dec),
        altitude: altitude(H, phi, c.dec)
    };
};


// sun times configuration (angle, morning name, evening name)

var times = SunCalc.times = [
    [-0.833, 'sunrise',       'sunset'      ],
    [  -0.3, 'sunriseEnd',    'sunsetStart' ],
    [    -6, 'dawn',          'dusk'        ],
    [   -12, 'nauticalDawn',  'nauticalDusk'],
    [   -18, 'nightEnd',      'night'       ],
    [     6, 'goldenHourEnd', 'goldenHour'  ]
];

// adds a custom time to the times config

SunCalc.addTime = function (angle, riseName, setName) {
    times.push([angle, riseName, setName]);
};


// calculations for sun times

var J0 = 0.0009;

function julianCycle(d, lw) { return Math.round(d - J0 - lw / (2 * PI)); }

function approxTransit(Ht, lw, n) { return J0 + (Ht + lw) / (2 * PI) + n; }
function solarTransitJ(ds, M, L)  { return J2000 + ds + 0.0053 * sin(M) - 0.0069 * sin(2 * L); }

function hourAngle(h, phi, d) { return acos((sin(h) - sin(phi) * sin(d)) / (cos(phi) * cos(d))); }
function observerAngle(height) { return -2.076 * Math.sqrt(height) / 60; }

// returns set time for the given sun altitude
function getSetJ(h, lw, phi, dec, n, M, L) {

    var w = hourAngle(h, phi, dec),
        a = approxTransit(w, lw, n);
    return solarTransitJ(a, M, L);
}


// calculates sun times for a given date, latitude/longitude, and, optionally,
// the observer height (in meters) relative to the horizon

SunCalc.getTimes = function (date, lat, lng, height) {

    height = height || 0;

    var lw = rad * -lng,
        phi = rad * lat,

        dh = observerAngle(height),

        d = toDays(date),
        n = julianCycle(d, lw),
        ds = approxTransit(0, lw, n),

        M = solarMeanAnomaly(ds),
        L = eclipticLongitude(M),
        dec = declination(L, 0),

        Jnoon = solarTransitJ(ds, M, L),

        i, len, time, h0, Jset, Jrise;


    var result = {
        solarNoon: fromJulian(Jnoon),
        nadir: fromJulian(Jnoon - 0.5)
    };

    for (i = 0, len = times.length; i < len; i += 1) {
        time = times[i];
        h0 = (time[0] + dh) * rad;

        Jset = getSetJ(h0, lw, phi, dec, n, M, L);
        Jrise = Jnoon - (Jset - Jnoon);

        result[time[1]] = fromJulian(Jrise);
        result[time[2]] = fromJulian(Jset);
    }

    return result;
};


// moon calculations, based on http://aa.quae.nl/en/reken/hemelpositie.html formulas

function moonCoords(d) { // geocentric ecliptic coordinates of the moon

    var L = rad * (218.316 + 13.176396 * d), // ecliptic longitude
        M = rad * (134.963 + 13.064993 * d), // mean anomaly
        F = rad * (93.272 + 13.229350 * d),  // mean distance

        l  = L + rad * 6.289 * sin(M), // longitude
        b  = rad * 5.128 * sin(F),     // latitude
        dt = 385001 - 20905 * cos(M);  // distance to the moon in km

    return {
        ra: rightAscension(l, b),
        dec: declination(l, b),
        dist: dt
    };
}

SunCalc.getMoonPosition = function (date, lat, lng) {

    var lw  = rad * -lng,
        phi = rad * lat,
        d   = toDays(date),

        c = moonCoords(d),
        H = siderealTime(d, lw) - c.ra,
        h = altitude(H, phi, c.dec),
        // formula 14.1 of "Astronomical Algorithms" 2nd edition by Jean Meeus (Willmann-Bell, Richmond) 1998.
        pa = atan(sin(H), tan(phi) * cos(c.dec) - sin(c.dec) * cos(H));

    h = h + astroRefraction(h); // altitude correction for refraction

    return {
        azimuth: azimuth(H, phi, c.dec),
        altitude: h,
        distance: c.dist,
        parallacticAngle: pa
    };
};


// calculations for illumination parameters of the moon,
// based on http://idlastro.gsfc.nasa.gov/ftp/pro/astro/mphase.pro formulas and
// Chapter 48 of "Astronomical Algorithms" 2nd edition by Jean Meeus (Willmann-Bell, Richmond) 1998.

SunCalc.getMoonIllumination = function (date) {

    var d = toDays(date || new Date()),
        s = sunCoords(d),
        m = moonCoords(d),

        sdist = 149598000, // distance from Earth to Sun in km

        phi = acos(sin(s.dec) * sin(m.dec) + cos(s.dec) * cos(m.dec) * cos(s.ra - m.ra)),
        inc = atan(sdist * sin(phi), m.dist - sdist * cos(phi)),
        angle = atan(cos(s.dec) * sin(s.ra - m.ra), sin(s.dec) * cos(m.dec) -
                cos(s.dec) * sin(m.dec) * cos(s.ra - m.ra));

    return {
        fraction: (1 + cos(inc)) / 2,
        phase: 0.5 + 0.5 * inc * (angle < 0 ? -1 : 1) / Math.PI,
        angle: angle
    };
};


function hoursLater(date, h) {
    return new Date(date.valueOf() + h * dayMs / 24);
}

// calculations for moon rise/set times are based on http://www.stargazing.net/kepler/moonrise.html article

SunCalc.getMoonTimes = function (date, lat, lng, inUTC) {
    var t = new Date(date);
    if (inUTC) t.setUTCHours(0, 0, 0, 0);
    else t.setHours(0, 0, 0, 0);

    var hc = 0.133 * rad,
        h0 = SunCalc.getMoonPosition(t, lat, lng).altitude - hc,
        h1, h2, rise, set, a, b, xe, ye, d, roots, x1, x2, dx;

    // go in 2-hour chunks, each time seeing if a 3-point quadratic curve crosses zero (which means rise or set)
    for (var i = 1; i <= 24; i += 2) {
        h1 = SunCalc.getMoonPosition(hoursLater(t, i), lat, lng).altitude - hc;
        h2 = SunCalc.getMoonPosition(hoursLater(t, i + 1), lat, lng).altitude - hc;

        a = (h0 + h2) / 2 - h1;
        b = (h2 - h0) / 2;
        xe = -b / (2 * a);
        ye = (a * xe + b) * xe + h1;
        d = b * b - 4 * a * h1;
        roots = 0;

        if (d >= 0) {
            dx = Math.sqrt(d) / (Math.abs(a) * 2);
            x1 = xe - dx;
            x2 = xe + dx;
            if (Math.abs(x1) <= 1) roots++;
            if (Math.abs(x2) <= 1) roots++;
            if (x1 < -1) x1 = x2;
        }

        if (roots === 1) {
            if (h0 < 0) rise = i + x1;
            else set = i + x1;

        } else if (roots === 2) {
            rise = i + (ye < 0 ? x2 : x1);
            set = i + (ye < 0 ? x1 : x2);
        }

        if (rise && set) break;

        h0 = h2;
    }

    var result = {};

    if (rise) result.rise = hoursLater(t, rise);
    if (set) result.set = hoursLater(t, set);

    if (!rise && !set) result[ye > 0 ? 'alwaysUp' : 'alwaysDown'] = true;

    return result;
};


// export as Node module / AMD module / browser variable
var gSun = (typeof globalThis !== "undefined") ? globalThis : this; gSun.SunCalc = SunCalc;
if (typeof exports === 'object' && typeof module !== 'undefined') module.exports = SunCalc;
else if (typeof define === 'function' && define.amd) define(SunCalc);
else { var g = (typeof globalThis !== "undefined") ? globalThis : this; g.SunCalc = SunCalc; }

}());



var HOURLY_FORECAST_HOURS = 48;
var STALE_REFETCH_AFTER_MS = 15 * 60 * 1000;
var US_BOUNDS = { minLat: 24, maxLat: 50, minLon: -125, maxLon: -66 };
var POLLEN_CURRENT_PARAMS = 'us_aqi,pm10,pm2_5,ozone,nitrogen_dioxide,sulphur_dioxide,carbon_monoxide,alder_pollen,birch_pollen,grass_pollen,mugwort_pollen,olive_pollen,ragweed_pollen';
var POLLEN_HOURLY_PARAMS = 'alder_pollen,birch_pollen,grass_pollen,mugwort_pollen,olive_pollen,ragweed_pollen';
var POLLEN_FIELDS = ['tree_pollen','alder_pollen','birch_pollen','olive_pollen','grass_pollen','weed_pollen','mugwort_pollen','ragweed_pollen'];
var MAX_STATION_DISTANCE_KM = 50;
var MAX_COASTAL_ELEVATION_M = 20;


function averageEnsembleValues(values) {
    if (!Array.isArray(values) || values.length === 0) return null;
    const numbers = values.filter((value) => Number.isFinite(value));
    if (!numbers.length) return null;
    return numbers.reduce((sum, value) => sum + value, 0) / numbers.length;
}

function modeEnsembleValue(values, round = false) {
    if (!Array.isArray(values) || values.length === 0) return null;
    const counts = new Map();
    for (const rawValue of values) {
        if (!Number.isFinite(rawValue)) continue;
        const value = round ? Math.round(rawValue) : rawValue;
        counts.set(value, (counts.get(value) || 0) + 1);
    }
    if (!counts.size) return null;

    let bestValue = null;
    let bestCount = -1;
    for (const [value, count] of counts.entries()) {
        if (count > bestCount) {
            bestValue = value;
            bestCount = count;
        }
    }
    return bestValue;
}

function medianEnsembleValue(values) {
    if (!Array.isArray(values) || values.length === 0) return null;
    const sorted = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
    if (!sorted.length) return null;
    const mid = Math.floor(sorted.length / 2);
    if (sorted.length % 2 === 1) return sorted[mid];
    return (sorted[mid - 1] + sorted[mid]) / 2;
}

function medianFloorEnsembleValue(values) {
    if (!Array.isArray(values) || values.length === 0) return null;
    const sorted = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
    if (!sorted.length) return null;
    const mid = Math.floor(sorted.length / 2);
    // For even-length arrays, pick the lower-middle element instead of averaging.
    // This is for categorical data (WMO weather codes) where averaging produces
    // phantom codes (e.g. median of [51, 99] = 75 "heavy snow" instead of 51 "light drizzle").
    if (sorted.length % 2 === 0) return sorted[mid - 1];
    return sorted[mid];
}

function findEnsembleSeries(container, variable, options = {}) {
    if (!container || !variable) return [];
    const { excludeMember = false } = options;
    const keys = Object.keys(container);
    const series = [];
    for (const key of keys) {
        if (key === variable || key.startsWith(`${variable}_`)) {
            if (excludeMember && key.includes('member')) continue;
            const value = container[key];
            if (Array.isArray(value)) {
                series.push(value);
            }
        }
    }
    return series;
}

function findEnsembleUnit(unitsContainer, variable, options = {}) {
    if (!unitsContainer || !variable) return undefined;
    const { excludeMember = false } = options;
    if (unitsContainer[variable]) return unitsContainer[variable];
    const unitKey = Object.keys(unitsContainer).find((key) => {
        if (!key.startsWith(`${variable}_`)) return false;
        if (excludeMember && key.includes('member')) return false;
        return true;
    });
    return unitKey ? unitsContainer[unitKey] : undefined;
}

function aggregateEnsembleSeries(seriesList, strategy = 'average', expectedLength = null) {
    if (!seriesList.length) return null;
    // Use expectedLength (time array length) as the source of truth when provided,
    // otherwise fall back to Math.max on series lengths
    const length = expectedLength !== null && expectedLength !== undefined
        ? expectedLength
        : Math.max(...seriesList.map((series) => series.length));
    const result = new Array(length).fill(null);

    for (let i = 0; i < length; i++) {
        const memberValues = seriesList.map((series) => series[i]).filter((value) => value !== undefined && value !== null);
        if (!memberValues.length) continue;

        if (strategy === 'mode') {
            result[i] = modeEnsembleValue(memberValues, true);
        } else if (strategy === 'median') {
            result[i] = medianEnsembleValue(memberValues);
        } else if (strategy === 'medianFloor') {
            result[i] = medianFloorEnsembleValue(memberValues);
        } else if (strategy === 'binary') {
            const avg = averageEnsembleValues(memberValues);
            result[i] = avg === null ? null : (avg >= 0.5 ? 1 : 0);
        } else {
            result[i] = averageEnsembleValues(memberValues);
        }
    }

    return result;
}

function roundTo(value, decimals) {
    if (!Number.isFinite(value)) return value;
    const factor = 10 ** decimals;
    return Math.round(value * factor) / factor;
}

function normalizeAggregatedSeries(series, options = {}) {
    if (!Array.isArray(series)) return series;
    const { decimals = null, clampAbsBelow = null } = options;
    return series.map((value) => {
        if (!Number.isFinite(value)) return value;
        let next = value;
        if (decimals !== null) {
            next = roundTo(next, decimals);
        }
        if (clampAbsBelow !== null && Math.abs(next) < clampAbsBelow) {
            return 0;
        }
        return next;
    });
}

function deriveEnsemblePrecipitationProbability(hourlyData, threshold = 0.01, expectedLength = null) {
    if (!hourlyData) return null;

    const memberSeries = Object.keys(hourlyData)
        .filter((key) => (
            key.startsWith('precipitation_') &&
            !key.startsWith('precipitation_probability') &&
            key.includes('member') &&
            Array.isArray(hourlyData[key])
        ))
        .map((key) => hourlyData[key]);

    if (!memberSeries.length) return null;

    // Use expectedLength (time array length) as the source of truth when provided,
    // otherwise fall back to Math.max on series lengths
    const length = expectedLength !== null && expectedLength !== undefined
        ? expectedLength
        : Math.max(...memberSeries.map((series) => series.length));
    const probability = new Array(length).fill(null);

    for (let i = 0; i < length; i++) {
        const membersWithRain = memberSeries.reduce((count, series) => {
            const value = series[i];
            return Number.isFinite(value) && value > threshold ? count + 1 : count;
        }, 0);
        probability[i] = Math.round((membersWithRain / memberSeries.length) * 100);
    }

    return probability;
}

function nearestTimeIndex(times, targetDate) {
    if (!Array.isArray(times) || !times.length) return 0;
    const targetMs = targetDate.getTime();
    let bestIndex = 0;
    let bestDelta = Number.POSITIVE_INFINITY;

    for (let i = 0; i < times.length; i++) {
        const timeMs = new Date(times[i]).getTime();
        if (!Number.isFinite(timeMs)) continue;
        const delta = Math.abs(timeMs - targetMs);
        if (delta < bestDelta) {
            bestDelta = delta;
            bestIndex = i;
        }
    }
    return bestIndex;
}

function summarizeDailyFromHourly(hourly, dates) {
    const dateIndexes = new Map();
    dates.forEach((date) => dateIndexes.set(date, []));

    for (let i = 0; i < hourly.time.length; i++) {
        const dateKey = hourly.time[i].split('T')[0];
        if (dateIndexes.has(dateKey)) {
            dateIndexes.get(dateKey).push(i);
        }
    }

    const result = {
        weather_code: [],
        temperature_2m_max: [],
        temperature_2m_min: [],
        apparent_temperature_max: [],
        apparent_temperature_min: [],
        precipitation_sum: [],
        wind_speed_10m_max: [],
        precipitation_probability_max: [],
        snowfall_sum: [],
        uv_index_max: []
    };

    const aggregateDay = (indexes, series, mode) => {
        if (!series || !indexes.length) return null;
        const values = indexes.map((idx) => series[idx]).filter((value) => Number.isFinite(value));
        if (!values.length) return null;
        if (mode === 'max') return Math.max(...values);
        if (mode === 'min') return Math.min(...values);
        if (mode === 'sum') return values.reduce((sum, value) => sum + value, 0);
        if (mode === 'mode') return modeEnsembleValue(values, true);
        if (mode === 'median') return medianEnsembleValue(values);
        if (mode === 'medianFloor') return medianFloorEnsembleValue(values);
        return averageEnsembleValues(values);
    };

    for (const date of dates) {
        const indexes = dateIndexes.get(date) || [];
        result.weather_code.push(aggregateDay(indexes, hourly.weather_code, 'medianFloor'));
        result.temperature_2m_max.push(aggregateDay(indexes, hourly.temperature_2m, 'max'));
        result.temperature_2m_min.push(aggregateDay(indexes, hourly.temperature_2m, 'min'));
        result.apparent_temperature_max.push(aggregateDay(indexes, hourly.apparent_temperature, 'max'));
        result.apparent_temperature_min.push(aggregateDay(indexes, hourly.apparent_temperature, 'min'));
        result.precipitation_sum.push(aggregateDay(indexes, hourly.precipitation, 'sum'));
        result.wind_speed_10m_max.push(aggregateDay(indexes, hourly.wind_speed_10m, 'max'));
        result.precipitation_probability_max.push(aggregateDay(indexes, hourly.precipitation_probability, 'max'));
        result.snowfall_sum.push(aggregateDay(indexes, hourly.snowfall, 'sum'));
        result.uv_index_max.push(aggregateDay(indexes, hourly.uv_index, 'max'));
    }

    return result;
}

function buildSunriseSunsetFromDates(dates, lat, lon) {
    return dates.map((dateKey) => {
        const day = parseDateString(dateKey);
        const times = SunCalc.getTimes(day, lat, lon);
        return {
            sunrise: times?.sunrise ? times.sunrise.toISOString() : null,
            sunset: times?.sunset ? times.sunset.toISOString() : null
        };
    });
}

function normalizeEnsembleWeatherData(rawData, lat, lon) {
    const normalized = {
        latitude: rawData.latitude,
        longitude: rawData.longitude,
        generationtime_ms: rawData.generationtime_ms,
        utc_offset_seconds: rawData.utc_offset_seconds,
        timezone: rawData.timezone,
        timezone_abbreviation: rawData.timezone_abbreviation,
        elevation: rawData.elevation,
        current_units: { time: 'iso8601' },
        current: {},
        hourly_units: { time: 'iso8601' },
        hourly: { time: rawData.hourly?.time ? [...rawData.hourly.time] : [] },
        daily_units: { time: 'iso8601' },
        daily: { time: [] }
    };

    const hourlyConfigs = [
        { source: 'temperature_2m', target: 'temperature_2m', strategy: 'average' },
        { source: 'relative_humidity_2m', target: 'relative_humidity_2m', strategy: 'average' },
        { source: 'weather_code', target: 'weather_code', strategy: 'medianFloor', excludeMember: true },
        { source: 'wind_speed_10m', target: 'wind_speed_10m', strategy: 'average' },
        { source: 'precipitation_probability', target: 'precipitation_probability', strategy: 'average', excludeMember: true },
        { source: 'precipitation', target: 'precipitation', strategy: 'average' },
        { source: 'snowfall', target: 'snowfall', strategy: 'average' },
        { source: 'surface_pressure', target: 'surface_pressure', strategy: 'average' },
        { source: 'cloud_cover', target: 'cloud_cover', strategy: 'average' },
        { source: 'cloud_cover_low', target: 'cloud_cover_low', strategy: 'average' },
        { source: 'cloud_cover_mid', target: 'cloud_cover_mid', strategy: 'average' },
        { source: 'cloud_cover_high', target: 'cloud_cover_high', strategy: 'average' },
        { source: 'shortwave_radiation', target: 'shortwave_radiation', strategy: 'average' },
        { source: 'is_day', target: 'is_day', strategy: 'binary' },
        { source: 'apparent_temperature', target: 'apparent_temperature', strategy: 'average' },
        { source: 'dew_point_2m', target: 'dewpoint_2m', strategy: 'average' },
        { source: 'uv_index', target: 'uv_index', strategy: 'average' }
    ];
    const hourlyPostProcess = {
        temperature_2m: { decimals: 0 },
        relative_humidity_2m: { decimals: 0 },
        wind_speed_10m: { decimals: 1 },
        precipitation_probability: { decimals: 0 },
        precipitation: { decimals: 2, clampAbsBelow: 0.01 },
        snowfall: { decimals: 2, clampAbsBelow: 0.1 },
        apparent_temperature: { decimals: 0 },
        dewpoint_2m: { decimals: 0 },
        uv_index: { decimals: 1 }
    };

    for (const config of hourlyConfigs) {
        const seriesList = findEnsembleSeries(rawData.hourly, config.source, {
            excludeMember: !!config.excludeMember
        });
        const aggregated = aggregateEnsembleSeries(seriesList, config.strategy, normalized.hourly.time.length);
        if (aggregated) {
            normalized.hourly[config.target] = normalizeAggregatedSeries(
                aggregated,
                hourlyPostProcess[config.target]
            );
            const unit = findEnsembleUnit(rawData.hourly_units, config.source, {
                excludeMember: !!config.excludeMember
            });
            if (unit) normalized.hourly_units[config.target] = unit;
        }
    }

    const derivedPrecipitationProbability = deriveEnsemblePrecipitationProbability(rawData.hourly, 0.01, normalized.hourly.time.length);
    if (derivedPrecipitationProbability) {
        normalized.hourly.precipitation_probability = derivedPrecipitationProbability;
        normalized.hourly_units.precipitation_probability = '%';
    }

    const dailyTime = rawData.daily?.time ? [...rawData.daily.time] : [...new Set(normalized.hourly.time.map((time) => time.split('T')[0]))];
    normalized.daily.time = dailyTime;

    const dailyConfigs = [
        { source: 'weather_code', target: 'weather_code', strategy: 'medianFloor', excludeMember: true },
        { source: 'temperature_2m_max', target: 'temperature_2m_max', strategy: 'average' },
        { source: 'temperature_2m_min', target: 'temperature_2m_min', strategy: 'average' },
        { source: 'apparent_temperature_max', target: 'apparent_temperature_max', strategy: 'average' },
        { source: 'apparent_temperature_min', target: 'apparent_temperature_min', strategy: 'average' },
        { source: 'precipitation_sum', target: 'precipitation_sum', strategy: 'average' },
        { source: 'wind_speed_10m_max', target: 'wind_speed_10m_max', strategy: 'average' },
        { source: 'precipitation_probability_max', target: 'precipitation_probability_max', strategy: 'average', excludeMember: true },
        { source: 'snowfall_sum', target: 'snowfall_sum', strategy: 'average' },
        { source: 'uv_index_max', target: 'uv_index_max', strategy: 'average' }
    ];
    const dailyPostProcess = {
        temperature_2m_max: { decimals: 0 },
        temperature_2m_min: { decimals: 0 },
        apparent_temperature_max: { decimals: 0 },
        apparent_temperature_min: { decimals: 0 },
        precipitation_sum: { decimals: 2, clampAbsBelow: 0.01 },
        wind_speed_10m_max: { decimals: 1 },
        precipitation_probability_max: { decimals: 0 },
        snowfall_sum: { decimals: 2, clampAbsBelow: 0.1 },
        uv_index_max: { decimals: 1 }
    };

    for (const config of dailyConfigs) {
        const seriesList = findEnsembleSeries(rawData.daily, config.source, {
            excludeMember: !!config.excludeMember
        });
        const aggregated = aggregateEnsembleSeries(seriesList, config.strategy, dailyTime.length);
        if (aggregated) {
            normalized.daily[config.target] = normalizeAggregatedSeries(
                aggregated,
                dailyPostProcess[config.target]
            );
            const unit = findEnsembleUnit(rawData.daily_units, config.source, {
                excludeMember: !!config.excludeMember
            });
            if (unit) normalized.daily_units[config.target] = unit;
        }
    }

    if (Array.isArray(normalized.hourly.precipitation_probability) && dailyTime.length) {
        const derivedDaily = summarizeDailyFromHourly(normalized.hourly, dailyTime);
        normalized.daily.precipitation_probability_max = normalizeAggregatedSeries(
            derivedDaily.precipitation_probability_max,
            dailyPostProcess.precipitation_probability_max
        );
        normalized.daily_units.precipitation_probability_max = '%';
    }

    const sunriseSeries = findEnsembleSeries(rawData.daily, 'sunrise');
    const sunsetSeries = findEnsembleSeries(rawData.daily, 'sunset');
    if (sunriseSeries.length) normalized.daily.sunrise = [...sunriseSeries[0]];
    if (sunsetSeries.length) normalized.daily.sunset = [...sunsetSeries[0]];
    if (normalized.daily.sunrise) normalized.daily_units.sunrise = 'iso8601';
    if (normalized.daily.sunset) normalized.daily_units.sunset = 'iso8601';

    const missingDailyFields = [
        'weather_code',
        'temperature_2m_max',
        'temperature_2m_min',
        'apparent_temperature_max',
        'apparent_temperature_min',
        'precipitation_sum',
        'wind_speed_10m_max',
        'precipitation_probability_max',
        'snowfall_sum',
        'uv_index_max'
    ].filter((field) => !normalized.daily[field]);

    if (missingDailyFields.length && normalized.hourly.time.length) {
        const derivedDaily = summarizeDailyFromHourly(normalized.hourly, dailyTime);
        for (const field of missingDailyFields) {
            normalized.daily[field] = normalizeAggregatedSeries(
                derivedDaily[field],
                dailyPostProcess[field]
            );
        }
    }

    if (!normalized.daily.sunrise || !normalized.daily.sunset) {
        const sunTimes = buildSunriseSunsetFromDates(dailyTime, lat, lon);
        if (!normalized.daily.sunrise) normalized.daily.sunrise = sunTimes.map((entry) => entry.sunrise);
        if (!normalized.daily.sunset) normalized.daily.sunset = sunTimes.map((entry) => entry.sunset);
        normalized.daily_units.sunrise = 'iso8601';
        normalized.daily_units.sunset = 'iso8601';
    }

    if (!normalized.daily_units.temperature_2m_max && normalized.hourly_units.temperature_2m) {
        normalized.daily_units.temperature_2m_max = normalized.hourly_units.temperature_2m;
    }
    if (!normalized.daily_units.temperature_2m_min && normalized.hourly_units.temperature_2m) {
        normalized.daily_units.temperature_2m_min = normalized.hourly_units.temperature_2m;
    }
    if (!normalized.daily_units.apparent_temperature_max && normalized.hourly_units.apparent_temperature) {
        normalized.daily_units.apparent_temperature_max = normalized.hourly_units.apparent_temperature;
    }
    if (!normalized.daily_units.apparent_temperature_min && normalized.hourly_units.apparent_temperature) {
        normalized.daily_units.apparent_temperature_min = normalized.hourly_units.apparent_temperature;
    }
    // Hardcode units since ensemble API uses suffixed keys that findEnsembleUnit may miss
    if (!normalized.hourly_units.temperature_2m) normalized.hourly_units.temperature_2m = '°F';
    if (!normalized.hourly_units.relative_humidity_2m) normalized.hourly_units.relative_humidity_2m = '%';
    if (!normalized.hourly_units.wind_speed_10m) normalized.hourly_units.wind_speed_10m = 'mp/h';
    if (!normalized.hourly_units.precipitation) normalized.hourly_units.precipitation = 'inch';
    if (!normalized.hourly_units.snowfall) normalized.hourly_units.snowfall = 'inch';
    if (!normalized.hourly_units.surface_pressure) normalized.hourly_units.surface_pressure = 'hPa';
    if (!normalized.hourly_units.apparent_temperature) normalized.hourly_units.apparent_temperature = '°F';
    if (!normalized.hourly_units.dewpoint_2m) normalized.hourly_units.dewpoint_2m = '°F';
    if (!normalized.hourly_units.uv_index) normalized.hourly_units.uv_index = '';
    if (!normalized.daily_units.precipitation_sum) {
        normalized.daily_units.precipitation_sum = 'inch';
    }
    if (!normalized.daily_units.snowfall_sum) {
        normalized.daily_units.snowfall_sum = 'inch';
    }
    if (!normalized.daily_units.wind_speed_10m_max && normalized.hourly_units.wind_speed_10m) {
        normalized.daily_units.wind_speed_10m_max = normalized.hourly_units.wind_speed_10m;
    }
    if (!normalized.daily_units.precipitation_probability_max) {
        normalized.daily_units.precipitation_probability_max = '%';
    }
    if (!normalized.daily_units.uv_index_max) {
        normalized.daily_units.uv_index_max = '';
    }
    if (!normalized.daily_units.weather_code) {
        normalized.daily_units.weather_code = 'wmo code';
    }

    const currentIndex = nearestTimeIndex(normalized.hourly.time, new Date());
    normalized.current.time = normalized.hourly.time[currentIndex] || new Date().toISOString();
    normalized.current.temperature_2m = normalized.hourly.temperature_2m?.[currentIndex];
    normalized.current.relative_humidity_2m = normalized.hourly.relative_humidity_2m?.[currentIndex];
    normalized.current.apparent_temperature = normalized.hourly.apparent_temperature?.[currentIndex];
    normalized.current.wind_speed_10m = normalized.hourly.wind_speed_10m?.[currentIndex];
    normalized.current.uv_index = normalized.hourly.uv_index?.[currentIndex];
    normalized.current.weather_code = normalized.hourly.weather_code?.[currentIndex];
    normalized.current.dewpoint_2m = normalized.hourly.dewpoint_2m?.[currentIndex];
    normalized.current.surface_pressure = normalized.hourly.surface_pressure?.[currentIndex];

    normalized.current_units.temperature_2m = normalized.hourly_units.temperature_2m;
    normalized.current_units.relative_humidity_2m = normalized.hourly_units.relative_humidity_2m;
    normalized.current_units.apparent_temperature = normalized.hourly_units.apparent_temperature;
    normalized.current_units.wind_speed_10m = normalized.hourly_units.wind_speed_10m;
    normalized.current_units.uv_index = normalized.hourly_units.uv_index || '';
    normalized.current_units.weather_code = normalized.hourly_units.weather_code || 'wmo code';
    normalized.current_units.dewpoint_2m = normalized.hourly_units.dewpoint_2m;
    normalized.current_units.surface_pressure = normalized.hourly_units.surface_pressure;

    return normalized;
}

function isLikelyUsLocation(lat, lon) {
    return lat >= US_BOUNDS.minLat &&
        lat <= US_BOUNDS.maxLat &&
        lon >= US_BOUNDS.minLon &&
        lon <= US_BOUNDS.maxLon;
}

function extractDurationHours(duration) {
    if (!duration) return 0;
    const dayMatch = duration.match(/(\d+)D/);
    const hourMatch = duration.match(/(\d+)H/);
    const minuteMatch = duration.match(/(\d+)M/);
    const days = dayMatch ? Number(dayMatch[1]) : 0;
    const hours = hourMatch ? Number(hourMatch[1]) : 0;
    const minutes = minuteMatch ? Number(minuteMatch[1]) : 0;
    return days * 24 + hours + (minutes / 60);
}

function overlapHours(rangeStart, rangeEnd, targetStart, targetEnd) {
    const start = Math.max(rangeStart.getTime(), targetStart.getTime());
    const end = Math.min(rangeEnd.getTime(), targetEnd.getTime());
    if (end <= start) return 0;
    return (end - start) / (1000 * 60 * 60);
}

function formatDateYYYYMMDD(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}${month}${day}`;
}

function formatDateKey(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function parseNoaaDateTime(dateTimeString) {
    if (!dateTimeString || typeof dateTimeString !== 'string') return null;
    const [datePart, timePart] = dateTimeString.trim().split(' ');
    if (!datePart || !timePart) return null;
    const [year, month, day] = datePart.split('-').map(Number);
    const [hours, minutes] = timePart.split(':').map(Number);
    if (![year, month, day, hours, minutes].every(Number.isFinite)) return null;
    return new Date(year, month - 1, day, hours, minutes, 0, 0);
}

function haversineKm(lat1, lon1, lat2, lon2) {
    const toRad = (value) => value * Math.PI / 180;
    const earthRadiusKm = 6371;
    const dLat = toRad(lat2 - lat1);
    const dLon = toRad(lon2 - lon1);
    const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) *
        Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return earthRadiusKm * c;
}

function normalizeNoaaStations(rawStations) {
    if (!Array.isArray(rawStations)) return [];

    return rawStations
        .map((station) => {
            const lat = Number(station?.lat);
            const lon = Number(station?.lng ?? station?.lon ?? station?.long);
            return {
                id: station?.id,
                name: station?.name || station?.id,
                lat,
                lon
            };
        })
        .filter((station) => station.id && Number.isFinite(station.lat) && Number.isFinite(station.lon));
}

function interpolateTideCurve(hiloPoints, intervalMinutes = 15) {
    if (!Array.isArray(hiloPoints) || hiloPoints.length < 2) return [];

    const sorted = hiloPoints
        .filter((point) => point?.time instanceof Date && Number.isFinite(point.value))
        .slice()
        .sort((a, b) => a.time.getTime() - b.time.getTime());

    if (sorted.length < 2) return [];

    const intervalMs = Math.max(1, Number(intervalMinutes) || 15) * 60 * 1000;
    const curve = [];
    const seen = new Set();

    const pushPoint = (timeMs, value) => {
        if (seen.has(timeMs) || !Number.isFinite(value)) return;
        seen.add(timeMs);
        curve.push({
            time: new Date(timeMs),
            value: Number(value.toFixed(3)),
            type: ''
        });
    };

    for (let i = 0; i < sorted.length - 1; i++) {
        const start = sorted[i];
        const end = sorted[i + 1];
        const startMs = start.time.getTime();
        const endMs = end.time.getTime();
        const spanMs = endMs - startMs;

        if (spanMs <= 0) continue;

        for (let tMs = startMs; tMs < endMs; tMs += intervalMs) {
            const t = (tMs - startMs) / spanMs;
            const value = start.value + (end.value - start.value) * ((1 - Math.cos(Math.PI * t)) / 2);
            pushPoint(tMs, value);
        }

        pushPoint(endMs, end.value);
    }

    return curve;
}

function buildTideDailySummaries(hiloPredictions, startDate, days) {
    const summaries = {};
    const start = new Date(startDate);
    start.setHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setDate(end.getDate() + days);

    hiloPredictions.forEach((entry) => {
        if (!entry?.time || !Number.isFinite(entry.value)) return;
        if (entry.time < start || entry.time > end) return;

        const dateKey = formatDateKey(entry.time);
        if (!summaries[dateKey]) {
            summaries[dateKey] = { high: null, low: null };
        }

        if (entry.type === 'H') {
            if (!summaries[dateKey].high || entry.value > summaries[dateKey].high.value) {
                summaries[dateKey].high = { value: entry.value, time: entry.time };
            }
        } else if (entry.type === 'L') {
            if (!summaries[dateKey].low || entry.value < summaries[dateKey].low.value) {
                summaries[dateKey].low = { value: entry.value, time: entry.time };
            }
        }
    });

    return summaries;
}

function parseNoaaPredictionRow(row) {
    const time = parseNoaaDateTime(row?.t);
    const value = Number(row?.v);
    if (!time || !Number.isFinite(value)) return null;
    return {
        time,
        value,
        type: (row?.type || '').toUpperCase()
    };
}

function getWeatherIconFile(code, isDay = true, precipProbability = null) {
    // Suppress rain/drizzle icons when precipitation probability is low (<= 30%)
    // Downgrade to partly cloudy instead
    if (precipProbability !== null && precipProbability <= 30) {
        const rainCodes = [51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82, 95, 96, 99];
        if (rainCodes.includes(code)) {
            code = 2; // Partly cloudy
        }
    }
    // WMO Weather interpretation codes mapped to vendored Meteocons fill icons
    // (MIT, Bas Milius) served by the Worker at /icons/weather/<file>.
    if (!isDay) {
        const nightFiles = {
            0: 'clear-night.svg', 1: 'mostly-clear-night.svg', 2: 'partly-cloudy-night.svg', 3: 'overcast-night.svg',
            45: 'fog-night.svg', 48: 'fog-night.svg',
            51: 'partly-cloudy-night-drizzle.svg', 53: 'partly-cloudy-night-drizzle.svg', 55: 'partly-cloudy-night-drizzle.svg',
            56: 'partly-cloudy-night-sleet.svg', 57: 'partly-cloudy-night-sleet.svg',
            61: 'partly-cloudy-night-rain.svg', 63: 'overcast-night-rain.svg', 65: 'extreme-night-rain.svg',
            66: 'partly-cloudy-night-sleet.svg', 67: 'overcast-night-sleet.svg',
            71: 'partly-cloudy-night-snow.svg', 73: 'overcast-night-snow.svg', 75: 'extreme-night-snow.svg',
            77: 'overcast-night-snow.svg',
            80: 'partly-cloudy-night-rain.svg', 81: 'overcast-night-rain.svg', 82: 'extreme-night-rain.svg',
            85: 'partly-cloudy-night-snow.svg', 86: 'overcast-night-snow.svg',
            95: 'thunderstorms-night-rain.svg', 96: 'thunderstorms-night-hail.svg', 99: 'thunderstorms-night-hail.svg'
        };
        return nightFiles[code] || 'clear-night.svg';
    }
    const dayFiles = {
        0: 'clear-day.svg', 1: 'mostly-clear-day.svg', 2: 'partly-cloudy-day.svg', 3: 'overcast-day.svg',
        45: 'fog-day.svg', 48: 'fog-day.svg',
        51: 'partly-cloudy-day-drizzle.svg', 53: 'partly-cloudy-day-drizzle.svg', 55: 'partly-cloudy-day-drizzle.svg',
        56: 'partly-cloudy-day-sleet.svg', 57: 'partly-cloudy-day-sleet.svg',
        61: 'partly-cloudy-day-rain.svg', 63: 'overcast-day-rain.svg', 65: 'extreme-day-rain.svg',
        66: 'partly-cloudy-day-sleet.svg', 67: 'overcast-day-sleet.svg',
        71: 'partly-cloudy-day-snow.svg', 73: 'overcast-day-snow.svg', 75: 'extreme-day-snow.svg',
        77: 'overcast-day-snow.svg',
        80: 'partly-cloudy-day-rain.svg', 81: 'overcast-day-rain.svg', 82: 'extreme-day-rain.svg',
        85: 'partly-cloudy-day-snow.svg', 86: 'overcast-day-snow.svg',
        95: 'thunderstorms-day-rain.svg', 96: 'thunderstorms-day-hail.svg', 99: 'thunderstorms-day-hail.svg'
    };
    return dayFiles[code] || 'clear-day.svg';
}

function getWeatherDescription(code) {
    const descriptions = {
        0: 'Clear sky', 1: 'Mainly clear', 2: 'Partly cloudy', 3: 'Overcast',
        45: 'Foggy', 48: 'Depositing rime fog',
        51: 'Light drizzle', 53: 'Moderate drizzle', 55: 'Dense drizzle',
        56: 'Light freezing drizzle', 57: 'Dense freezing drizzle',
        61: 'Slight rain', 63: 'Moderate rain', 65: 'Heavy rain',
        66: 'Light freezing rain', 67: 'Heavy freezing rain',
        71: 'Slight snow', 73: 'Moderate snow', 75: 'Heavy snow',
        77: 'Snow grains',
        80: 'Slight rain showers', 81: 'Moderate rain showers', 82: 'Violent rain showers',
        85: 'Slight snow showers', 86: 'Heavy snow showers',
        95: 'Thunderstorm', 96: 'Thunderstorm with slight hail', 99: 'Thunderstorm with heavy hail'
    };
    return descriptions[code] || 'Unknown';
}

function getAlertIconFile(eventType) {
    const event = String(eventType || '').toLowerCase();
    const has = (...needles) => needles.some((needle) => event.includes(needle));

    // Marine hurricane-force winds fly their own warning flag, so check
    // before the generic hurricane glyph below.
    if (has('hurricane force')) return 'flag-hurricane-warning.svg';
    if (has('tornado')) return 'tornado.svg';
    if (has('hurricane', 'tropical storm', 'typhoon')) return 'hurricane.svg';
    if (has('thunderstorm', 'severe weather', 'lightning')) return 'thunderstorms.svg';
    if (has('flood', 'storm surge', 'tsunami', 'rip current', 'beach hazard', 'lakeshore', 'hydrologic')) return 'water.svg';
    if (has('red flag', 'fire weather', 'fire warning', 'wildfire', 'smoke', 'air quality')) return 'smoke.svg';
    if (has('avalanche')) return 'alert-avalanche-danger.svg';
    if (has('fog')) return 'fog.svg';
    if (has('dust')) return 'dust.svg';
    if (has('heat')) return 'sun-hot.svg';
    if (has('winter storm', 'winter weather', 'blizzard', 'ice storm', 'freezing rain', 'freezing drizzle', 'sleet', 'lake effect', 'snow squall', 'snow')) return 'snowflake.svg';
    if (has('freeze', 'frost', 'cold', 'wind chill')) return 'flag-cold-wave.svg';
    if (has('small craft')) return 'flag-small-craft-advisory.svg';
    if (has('high wind', 'wind advisory', 'wind warning', 'wind watch', 'gale', 'lake wind', 'extreme wind', 'strong wind')) return 'flag-gale-warning.svg';
    if (has('storm warning', 'storm watch', 'special marine')) return 'flag-storm-warning.svg';
    return 'weather-alarm.svg';
}

function calculateMoonPhase(date) {
    // Calculate days since known new moon (January 6, 2000 18:14 UTC)
    const knownNewMoon = new Date('2000-01-06T18:14:00Z');
    const daysSinceNewMoon = (date - knownNewMoon) / (1000 * 60 * 60 * 24);

    // Moon cycle is approximately 29.53058867 days
    const moonCycle = 29.53058867;
    const phase = (daysSinceNewMoon % moonCycle) / moonCycle;

    // Ensure phase is between 0 and 1
    return phase < 0 ? phase + 1 : phase;
}

function getMoonPhase(phase) {
    // Moon phase is a value from 0 to 1
    // 0 = New Moon, 0.25 = First Quarter, 0.5 = Full Moon, 0.75 = Last Quarter
    if (phase === null || phase === undefined) return { emoji: '🌑', name: 'Unknown' };

    if (phase < 0.03 || phase >= 0.97) {
        return { emoji: '🌑', name: 'New Moon' };
    } else if (phase >= 0.03 && phase < 0.22) {
        return { emoji: '🌒', name: 'Waxing Crescent' };
    } else if (phase >= 0.22 && phase < 0.28) {
        return { emoji: '🌓', name: 'First Quarter' };
    } else if (phase >= 0.28 && phase < 0.47) {
        return { emoji: '🌔', name: 'Waxing Gibbous' };
    } else if (phase >= 0.47 && phase < 0.53) {
        return { emoji: '🌕', name: 'Full Moon' };
    } else if (phase >= 0.53 && phase < 0.72) {
        return { emoji: '🌖', name: 'Waning Gibbous' };
    } else if (phase >= 0.72 && phase < 0.78) {
        return { emoji: '🌗', name: 'Last Quarter' };
    } else {
        return { emoji: '🌘', name: 'Waning Crescent' };
    }
}

function getMoonIllumination(date) {
    // Use SunCalc to get accurate moon illumination
    // Returns illuminated fraction (0 to 1), convert to percentage
    const moonIllumination = SunCalc.getMoonIllumination(date);
    return Math.round(moonIllumination.fraction * 100);
}

function calculateMoonDistance(date, lat, lon) {
    // Use SunCalc to get accurate moon distance
    // Distance is returned in kilometers, convert to miles
    const moonPosition = SunCalc.getMoonPosition(date, lat, lon);
    // Distance is in kilometers, convert to miles (1 km = 0.621371 miles)
    const distanceInMiles = moonPosition.distance * 0.621371;
    return Math.round(distanceInMiles);
}

function calculateMoonRiseSet(date, lat, lon) {
    // Use SunCalc to get accurate moonrise/moonset times
    const moonTimes = SunCalc.getMoonTimes(date, lat, lon);

    // SunCalc returns Date objects or null if moon doesn't rise/set that day
    return {
        rise: moonTimes.rise || null,
        set: moonTimes.set || null,
        alwaysUp: moonTimes.alwaysUp || false,
        alwaysDown: moonTimes.alwaysDown || false
    };
}

function getNextFullMoon(date) {
    const currentPhase = calculateMoonPhase(date);
    let daysToFull = 0;

    if (currentPhase < 0.5) {
        // Before full moon
        daysToFull = (0.5 - currentPhase) * 29.53058867;
    } else {
        // After full moon, next one is in next cycle
        daysToFull = (1.5 - currentPhase) * 29.53058867;
    }

    const nextFullMoon = new Date(date);
    nextFullMoon.setDate(nextFullMoon.getDate() + Math.round(daysToFull));
    return { date: nextFullMoon, days: Math.round(daysToFull) };
}

function getNextNewMoon(date) {
    const currentPhase = calculateMoonPhase(date);
    let daysToNew = 0;

    if (currentPhase < 0.97) {
        // Before new moon
        daysToNew = (1 - currentPhase) * 29.53058867;
    } else {
        // Very close to new moon, next one is in next cycle
        daysToNew = (1 - currentPhase + 1) * 29.53058867;
    }

    const nextNewMoon = new Date(date);
    nextNewMoon.setDate(nextNewMoon.getDate() + Math.round(daysToNew));
    return { date: nextNewMoon, days: Math.round(daysToNew) };
}

function formatTime12Hour(date) {
    let hours = date.getHours();
    const minutes = date.getMinutes();
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12; // the hour '0' should be '12'
    const minutesStr = minutes < 10 ? '0' + minutes : minutes;
    return `${hours}:${minutesStr} ${ampm}`;
}

function parseDateString(dateString) {
    // Parse date string (format: "YYYY-MM-DD") as local date, not UTC
    // This prevents timezone issues where UTC dates shift to previous day
    const parts = dateString.split('-');
    if (parts.length === 3) {
        const year = parseInt(parts[0], 10);
        const month = parseInt(parts[1], 10) - 1; // Month is 0-indexed
        const day = parseInt(parts[2], 10);
        return new Date(year, month, day);
    }
    // Fallback to regular Date parsing if format is different
    return new Date(dateString);
}

function formatLastUpdatedBetween(nowMs, fetchTimeMs) {
    if (!Number.isFinite(nowMs) || !Number.isFinite(fetchTimeMs)) return 'just now';
    const diffMins = Math.floor(Math.max(0, nowMs - fetchTimeMs) / 60000);
    if (diffMins < 1) return 'just now';
    if (diffMins === 1) return '1 minute ago';
    if (diffMins < 60) return `${diffMins} minutes ago`;
    const diffHours = Math.floor(diffMins / 60);
    return diffHours === 1 ? '1 hour ago' : `${diffHours} hours ago`;
}

// Pure: refetch only when we have a recorded fetch older than the threshold.
// Short hidden/focus flickers under the threshold never trigger a fetch.
function shouldRefetchStaleForecast(nowMs, lastFetchMs, staleAfterMs = STALE_REFETCH_AFTER_MS) {
    if (!Number.isFinite(nowMs) || !Number.isFinite(lastFetchMs) || lastFetchMs <= 0) return false;
    if (!Number.isFinite(staleAfterMs) || staleAfterMs < 0) return false;
    return (nowMs - lastFetchMs) >= staleAfterMs;
}

function parseLocationLocalIso(iso, utcOffsetSeconds = 0) {
    if (!iso) return NaN;
    const s = String(iso);
    if (/[zZ]$|[+-]\d{2}:?\d{2}$/.test(s)) {
        const ms = new Date(s).getTime();
        return Number.isFinite(ms) ? ms : NaN;
    }
    const m = s.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?/);
    if (!m) {
        const ms = new Date(s).getTime();
        return Number.isFinite(ms) ? ms : NaN;
    }
    const asUtc = Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +(m[6] || 0));
    return asUtc - (Number(utcOffsetSeconds) || 0) * 1000;
}

// Format Open-Meteo local wall clock without shifting into the browser timezone
function formatIsoLocalClock(iso) {
    const m = String(iso || '').match(/T(\d{2}):(\d{2})/);
    if (!m) return formatTime12Hour(new Date(iso));
    let h = parseInt(m[1], 10);
    const mi = m[2];
    const ampm = h >= 12 ? 'PM' : 'AM';
    h = h % 12 || 12;
    return `${h}:${mi} ${ampm}`;
}

// Format a real UTC instant (SunCalc moonrise/moonset) in the selected
// location's offset, not the browser timezone. SunCalc returns true instants,
// so shift by utc_offset_seconds to get location wall-clock. Do NOT use
// formatIsoLocalClock here: it reads naive Open-Meteo ISOs verbatim and would
// misread a `...Z` ISO as if UTC were already local.
function formatInstantInLocation(instant, utcOffsetSeconds = 0) {
    const ms = instant instanceof Date ? instant.getTime() : new Date(instant).getTime();
    if (!Number.isFinite(ms)) return 'N/A';
    const shifted = new Date(ms + (Number(utcOffsetSeconds) || 0) * 1000);
    let h = shifted.getUTCHours();
    const mi = String(shifted.getUTCMinutes()).padStart(2, '0');
    const ampm = h >= 12 ? 'PM' : 'AM';
    h = h % 12 || 12;
    return `${h}:${mi} ${ampm}`;
}

function hpaToInhg(hpa) {
    return hpa * 0.02953;
}

// Calculate daily averages from hourly data for a specific date
function calculateDailyAverages(hourlyData, targetDate) {
    const targetDateStr = targetDate.toISOString().split('T')[0];
    return calculateDailyAveragesForDateString(hourlyData, targetDateStr);
}

function calculateDailyAveragesForDateString(hourlyData, targetDateStr) {
    if (!hourlyData || !hourlyData.time || !targetDateStr) return null;

    let tempSum = 0, humiditySum = 0, pressureSum = 0, precipSum = 0;
    let windMax = 0, count = 0;

    for (let i = 0; i < hourlyData.time.length; i++) {
        const hourDate = hourlyData.time[i].split('T')[0];
        if (hourDate === targetDateStr) {
            tempSum += hourlyData.temperature_2m[i] || 0;
            humiditySum += hourlyData.relative_humidity_2m[i] || 0;
            pressureSum += hourlyData.surface_pressure ? (hourlyData.surface_pressure[i] || 0) : 0;
            precipSum += hourlyData.precipitation ? (hourlyData.precipitation[i] || 0) : 0;
            windMax = Math.max(windMax, hourlyData.wind_speed_10m[i] || 0);
            count++;
        }
    }

    if (count === 0) return null;

    return {
        avgTemp: tempSum / count,
        avgHumidity: humiditySum / count,
        avgPressureInhg: hpaToInhg(pressureSum / count),
        precipSum: precipSum,
        windMax: windMax
    };
}

// Simplified sinus risk score (0-4): pressure-led, plain language.
// Pressure does most of the work; damp air or a big temp swing adds at most +1.
// 0-1 = Low, 2 = Elevated, 3-4 = High.
function calculateSinusRisk(pressureChange, humidity, precipitation, tempSwing) {
    let risk = 0;

    // Pressure trend (day-over-day change, inHg)
    if (pressureChange < -0.25) {
        risk += 3; // Falling fast
    } else if (pressureChange < -0.10) {
        risk += 2; // Falling
    }

    // Damp or swingy days add a little (capped at +1 total)
    const isDamp = humidity > 70 || precipitation > 0.1;
    const isSwingy = tempSwing > 20;
    if (isDamp || isSwingy) {
        risk += 1;
    }

    // Clip to 0-4
    return Math.max(0, Math.min(4, risk));
}

// Plain-language pressure trend for display (no inHg decimals for users)
function getPressureTrend(pressureChange) {
    if (pressureChange < -0.25) {
        return { label: 'Falling fast', arrow: '↓' };
    } else if (pressureChange < -0.10) {
        return { label: 'Falling', arrow: '↓' };
    }
    return { label: 'Steady', arrow: '→' };
}

// Short driver phrases for the sinus card (max 2, plain language)
function getSinusDrivers(pressureChange, humidity, precipitation, tempSwing) {
    const drivers = [];
    const trend = getPressureTrend(pressureChange);
    if (trend.label === 'Falling fast') {
        drivers.push('Falling fast');
    } else if (trend.label === 'Falling') {
        drivers.push('Falling pressure');
    }
    if (precipitation > 0.1) {
        drivers.push('Rain');
    } else if (humidity > 70) {
        drivers.push('Humid');
    } else if (tempSwing > 20) {
        drivers.push('Large temp swing');
    }
    if (drivers.length === 0) {
        drivers.push('Steady pressure');
    }
    return drivers.slice(0, 2);
}

// Simple 3-level label shared by sinus + allergy: Low / Elevated / High
function getSimpleRiskLabel(score) {
    if (score === null || score === undefined) {
        return { label: 'No data', colorClass: 'text-gray-400' };
    }
    if (score <= 1) {
        return { label: 'Low', colorClass: 'text-green-400' };
    } else if (score <= 2) {
        return { label: 'Elevated', colorClass: 'text-yellow-400' };
    }
    return { label: 'High', colorClass: 'text-orange-400' };
}

// Simplified allergy risk score (0-3): driven by pollen level only.
// Wind/rain don't change the score; they're shown alongside the result
// ("Windy" / "Rain") without affecting it.
// 0-1 = Low, 2 = Elevated, 3 = High.
function calculateAllergyRisk(windMax, precipitation, pollenData = null) {
    // Requires actual pollen values. Null/undefined means unavailable, not zero.
    if (!pollenData || !hasAnyPollenData(pollenData.current)) {
        return null;
    }

    const current = pollenData.current;

    // Get max pollen levels
    const treePollen = maxAvailablePollen([
        current.tree_pollen,
        current.alder_pollen,
        current.birch_pollen,
        current.olive_pollen
    ]);
    const grassPollen = maxAvailablePollen([current.grass_pollen]);
    const weedPollen = maxAvailablePollen([
        current.weed_pollen,
        current.mugwort_pollen,
        current.ragweed_pollen
    ]);
    const maxPollen = maxAvailablePollen([treePollen, grassPollen, weedPollen]);

    // Map the worst pollen category straight to risk (grains/m³ bands
    // match getPollenLevel so the tile and the pollen section agree)
    if (maxPollen === null || maxPollen === undefined || maxPollen <= 20) {
        return 1; // None/Low pollen -> Low
    } else if (maxPollen <= 80) {
        return 2; // Moderate pollen -> Elevated
    }
    return 3; // High/Very High pollen -> High
}

// Dominant pollen type + wind/rain helper notes for the allergy card
function getAllergyDrivers(pollenData, windMax, precipitation) {
    const drivers = [];
    if (pollenData && pollenData.current) {
        const current = pollenData.current;
        const treePollen = maxAvailablePollen([
            current.tree_pollen, current.alder_pollen,
            current.birch_pollen, current.olive_pollen
        ]);
        const grassPollen = maxAvailablePollen([current.grass_pollen]);
        const weedPollen = maxAvailablePollen([
            current.weed_pollen, current.mugwort_pollen,
            current.ragweed_pollen
        ]);
        const ranked = [
            { name: 'Tree pollen', value: treePollen },
            { name: 'Grass pollen', value: grassPollen },
            { name: 'Weed pollen', value: weedPollen }
        ].filter(p => p.value !== null && p.value !== undefined && p.value > 0)
         .sort((a, b) => b.value - a.value);
        if (ranked.length > 0) {
            drivers.push(ranked[0].name);
        }
    }
    if (windMax > 10) {
        drivers.push('Windy');
    }
    if (precipitation > 0.1) {
        drivers.push('Rain');
    }
    if (drivers.length === 0) {
        drivers.push('Low pollen');
    }
    return drivers.slice(0, 2);
}

function calculateNiceWeatherIndex(data, todayAvg, todayIndex) {
    const breakdown = getNiceWeatherBreakdown(data, todayAvg, todayIndex);
    return breakdown ? breakdown.score : null;
}

function getNiceWeatherBreakdown(data, todayAvg, todayIndex) {
    if (!data || !todayAvg) return null;

    const avgTemp = todayAvg.avgTemp;
    const avgHumidity = todayAvg.avgHumidity;
    const precipSum = todayAvg.precipSum;
    const windMax = todayAvg.windMax;
    const uvIndex = data.current?.uv_index ?? 0;
    const precipProbability = data.daily?.precipitation_probability_max?.[todayIndex] ?? 0;
    const cloudCover = getAverageHourlyValueForDate(data.hourly, 'cloud_cover', data.daily?.time?.[todayIndex]);
    const weatherCode = data.daily?.weather_code?.[todayIndex];
    const weatherDescription = getWeatherDescription(weatherCode);

    if ([avgTemp, avgHumidity, precipSum, windMax].some(value => value === null || value === undefined || Number.isNaN(value))) {
        return null;
    }

    let score = 10;
    const factors = [];

    function addFactor(name, value, points, note, iconClass) {
        factors.push({ name, value, points, note, iconClass });
        score -= points;
    }

    // Temperature comfort sweet spot is roughly 65-78°F.
    if (avgTemp < 50) addFactor('Temperature', `${avgTemp.toFixed(0)}°F avg`, 4, 'Too cold for most outdoor comfort', 'fas fa-thermometer-half text-blue-300');
    else if (avgTemp < 60) addFactor('Temperature', `${avgTemp.toFixed(0)}°F avg`, 2, 'Cooler than the 65–78°F sweet spot', 'fas fa-thermometer-half text-blue-300');
    else if (avgTemp > 92) addFactor('Temperature', `${avgTemp.toFixed(0)}°F avg`, 4, 'Very hot for outdoor comfort', 'fas fa-thermometer-half text-red-300');
    else if (avgTemp > 85) addFactor('Temperature', `${avgTemp.toFixed(0)}°F avg`, 2, 'Hotter than ideal', 'fas fa-thermometer-half text-orange-300');
    else if (avgTemp > 78) addFactor('Temperature', `${avgTemp.toFixed(0)}°F avg`, 1, 'A little warm versus the comfort sweet spot', 'fas fa-thermometer-half text-yellow-300');
    else factors.push({ name: 'Temperature', value: `${avgTemp.toFixed(0)}°F avg`, points: 0, note: 'Comfortable 65–78°F range', iconClass: 'fas fa-thermometer-half text-green-300' });

    // Rain and high rain odds make otherwise pleasant weather less nice.
    if (precipSum > 0.5) addFactor('Precipitation', `${precipSum.toFixed(2)} in`, 3, 'Wet day expected', 'fas fa-cloud-rain text-blue-300');
    else if (precipSum > 0.1) addFactor('Precipitation', `${precipSum.toFixed(2)} in`, 2, 'Some rain expected', 'fas fa-cloud-rain text-blue-300');
    else if (precipSum > 0) addFactor('Precipitation', `${precipSum.toFixed(2)} in`, 1, 'Light precipitation possible', 'fas fa-cloud-rain text-blue-300');
    else factors.push({ name: 'Precipitation', value: `${precipSum.toFixed(2)} in`, points: 0, note: 'Dry conditions', iconClass: 'fas fa-cloud-rain text-green-300' });

    if (precipProbability >= 70) addFactor('Rain odds', `${precipProbability}%`, 2, 'High chance of precipitation', 'fas fa-umbrella text-blue-300');
    else if (precipProbability >= 40) addFactor('Rain odds', `${precipProbability}%`, 1, 'Moderate chance of precipitation', 'fas fa-umbrella text-yellow-300');

    // Calm-to-light breezes score best.
    if (windMax > 25) addFactor('Wind', `${windMax.toFixed(1)} mph max`, 3, 'Very windy', 'fas fa-wind text-orange-300');
    else if (windMax > 18) addFactor('Wind', `${windMax.toFixed(1)} mph max`, 2, 'Windy', 'fas fa-wind text-yellow-300');
    else if (windMax > 12) addFactor('Wind', `${windMax.toFixed(1)} mph max`, 1, 'Breezy', 'fas fa-wind text-yellow-300');
    else factors.push({ name: 'Wind', value: `${windMax.toFixed(1)} mph max`, points: 0, note: 'Calm to light breeze', iconClass: 'fas fa-wind text-green-300' });

    // Muggy or very dry conditions reduce comfort.
    if (avgHumidity > 80) addFactor('Humidity', `${avgHumidity.toFixed(0)}% avg`, 2, 'Muggy', 'fas fa-tint text-blue-300');
    else if (avgHumidity > 65) addFactor('Humidity', `${avgHumidity.toFixed(0)}% avg`, 1, 'Humid', 'fas fa-tint text-blue-300');
    else if (avgHumidity < 25) addFactor('Humidity', `${avgHumidity.toFixed(0)}% avg`, 1, 'Very dry', 'fas fa-tint text-yellow-300');
    else factors.push({ name: 'Humidity', value: `${avgHumidity.toFixed(0)}% avg`, points: 0, note: 'Comfortable humidity', iconClass: 'fas fa-tint text-green-300' });

    // Too much cloud cover and very high UV both detract from "nice" outdoor weather.
    if (cloudCover !== null && cloudCover !== undefined) {
        if (cloudCover > 85) addFactor('Cloud/weather', `${cloudCover.toFixed(0)}% clouds, ${weatherDescription}`, 2, 'Very cloudy or overcast', 'fas fa-cloud text-gray-300');
        else if (cloudCover > 65) addFactor('Cloud/weather', `${cloudCover.toFixed(0)}% clouds, ${weatherDescription}`, 1, 'Mostly cloudy', 'fas fa-cloud text-gray-300');
        else factors.push({ name: 'Cloud/weather', value: `${cloudCover.toFixed(0)}% clouds, ${weatherDescription}`, points: 0, note: 'Good sky conditions', iconClass: 'fas fa-cloud-sun text-green-300' });
    } else {
        factors.push({ name: 'Cloud/weather', value: weatherDescription, points: 0, note: 'Cloud cover unavailable', iconClass: 'fas fa-cloud-sun text-gray-300' });
    }

    if (uvIndex >= 9) addFactor('UV', `${uvIndex}`, 1, 'Very high UV', 'fas fa-sun text-orange-300');
    else factors.push({ name: 'UV', value: `${uvIndex}`, points: 0, note: 'UV not extreme', iconClass: 'fas fa-sun text-yellow-300' });

    const finalScore = Math.max(0, Math.min(10, Math.round(score)));
    return { score: finalScore, factors };
}

function getAverageHourlyValueForDate(hourlyData, field, targetDateStr) {
    if (!hourlyData || !hourlyData.time || !hourlyData[field] || !targetDateStr) return null;
    let sum = 0;
    let count = 0;

    for (let i = 0; i < hourlyData.time.length; i++) {
        if (hourlyData.time[i].split('T')[0] === targetDateStr && hourlyData[field][i] !== null && hourlyData[field][i] !== undefined) {
            sum += hourlyData[field][i];
            count++;
        }
    }

    return count > 0 ? sum / count : null;
}

function getNiceWeatherLabel(index) {
    if (index >= 8) {
        return { label: 'Excellent', colorClass: 'text-green-400' };
    } else if (index >= 6) {
        return { label: 'Nice', colorClass: 'text-lime-400' };
    } else if (index >= 4) {
        return { label: 'Fair', colorClass: 'text-yellow-400' };
    }
    return { label: 'Poor', colorClass: 'text-orange-400' };
}

// Get risk level label and color class

function hasPollenValue(value) {
    return value !== null && value !== undefined && Number.isFinite(Number(value));
}

function maxAvailablePollen(values) {
    const availableValues = values.filter(hasPollenValue).map(Number);
    if (availableValues.length === 0) return null;
    return Math.max(...availableValues);
}

function hasAnyPollenData(current) {
    return !!current && POLLEN_FIELDS.some(field => hasPollenValue(current[field]));
}

function formatPollenValue(value) {
    return hasPollenValue(value) ? Math.round(Number(value)) : '0';
}

function getPollenLevel(value, options = {}) {
    if (value === null || value === undefined) {
        return { label: 'None', colorClass: 'text-gray-400', level: 0 };
    } else if (value === 0) {
        return { label: 'None', colorClass: 'text-gray-400', level: 0 };
    } else if (value <= 20) {
        return { label: 'Low', colorClass: 'text-green-400', level: 1 };
    } else if (value <= 80) {
        return { label: 'Moderate', colorClass: 'text-yellow-400', level: 2 };
    } else if (value <= 200) {
        return { label: 'High', colorClass: 'text-orange-400', level: 3 };
    } else {
        return { label: 'Very High', colorClass: 'text-red-400', level: 4 };
    }
}

function shouldDisplayNullPollenAsNone(aqiData, fields, dayIndex = null) {
    const metadata = aqiData?.pollen_null_display_as_none;
    const flags = dayIndex === null ? metadata?.current : metadata?.hourly?.[dayIndex];
    if (!flags) return false;
    return fields.some(field => flags[field]);
}

// Display pollen data

function uvCategoryLabel(value) {
    const num = Number(value);
    if (!Number.isFinite(num)) return 'Low';
    if (num < 3) return 'Low';
    if (num < 6) return 'Moderate';
    if (num < 8) return 'High';
    if (num < 11) return 'Very high';
    return 'Extreme';
}

// Daily UV max from hourly values when daily uv_index_max is unavailable.
function maxHourlyUvForDateString(hourly, dateStr) {
    if (!hourly || !Array.isArray(hourly.time) || !Array.isArray(hourly.uv_index) || !dateStr) return null;
    let max = null;
    for (let h = 0; h < hourly.time.length; h++) {
        if (String(hourly.time[h]).split('T')[0] !== dateStr) continue;
        const value = hourly.uv_index[h];
        if (!Number.isFinite(value)) continue;
        if (max === null || value > max) max = value;
    }
    return max === null ? null : Math.round(max * 10) / 10;
}

// ─── 14-day / hourly expanded-view chart series ─────────
// First paint must draw ONLY the default series (temperature), even when
// the cloned <select> still reports value "all" while Temperature looks selected.
const DEFAULT_CHART_SERIES = 'temp';
const DAILY_CHART_TYPE_BY_KEY = {
    temp: 'temp',
    feelsLike: 'feelslike',
    niceWeather: 'niceweather',
    precip: 'precip',
    wind: 'wind',
    uv: 'uv',
    pressure: 'pressure',
    snow: 'snow',
    cloud: 'cloud',
    brightness: 'brightness',
    tides: 'tides',
    moonPhase: 'moon'
};

let dailyModalSelectedSeries = DEFAULT_CHART_SERIES;
let dailyChartsRendered = typeof Set === 'function' ? new Set() : { _s: {}, has(k) { return !!this._s[k]; }, add(k) { this._s[k] = 1; }, clear() { this._s = {}; } };

function hasNumericValue(value) {
  return value !== null && value !== undefined && Number.isFinite(Number(value));
}

function hasAnyUsablePollen(data) {
  if (!data?.current) return false;
  const pollenFields = ['tree_pollen','alder_pollen','birch_pollen','olive_pollen','grass_pollen','weed_pollen','mugwort_pollen','ragweed_pollen'];
  return pollenFields.some(f => hasNumericValue(data.current[f]));
}

function googleIndexToPollenValue(indexValue) {
  // Google Pollen API returns an index (typically 0-5), not grains/m³.
  // Scale it into the app's existing pollen value shape so the current UI and
  // allergy-risk code can continue to represent unavailable values as null.
  if (!hasNumericValue(indexValue)) return null;
  return Math.max(0, Number(indexValue)) * 50;
}

function maxAvailableGoogleValue(values) {
  const availableValues = values.filter(hasNumericValue).map(Number);
  if (availableValues.length === 0) return null;
  return Math.max(...availableValues);
}

function normalizeGoogleCode(value) {
  return String(value || '').trim().toUpperCase();
}

function getGooglePollenTypeCode(info) {
  return normalizeGoogleCode(info?.code || info?.typeCode || info?.pollenType || info?.displayName);
}

function getGooglePlantCode(info) {
  return normalizeGoogleCode(info?.code || info?.plantCode || info?.displayName);
}

function googleInfoHasUsableIndex(info) {
  return info?.inSeason !== false && info?.indexInfo && hasNumericValue(info.indexInfo.value);
}

function googleInfoIsPresentWithoutIndex(info) {
  return info && !info.indexInfo;
}

function typeCodeToAppField(typeCode) {
  const normalized = normalizeGoogleCode(typeCode);
  if (normalized === 'TREE') return 'tree';
  if (normalized === 'GRASS') return 'grass';
  if (normalized === 'WEED') return 'weed';
  return null;
}

function plantCodeToAppField(plantCode) {
  const normalized = normalizeGoogleCode(plantCode);
  const plantMap = {
    ALDER: 'alder_pollen',
    BIRCH: 'birch_pollen',
    OLIVE: 'olive_pollen',
    GRAMINALES: 'grass_pollen',
    GRASS: 'grass_pollen',
    RAGWEED: 'ragweed_pollen',
    MUGWORT: 'mugwort_pollen',
  };
  return plantMap[normalized] || null;
}

function normalizeGooglePollen(googleData) {
  const dailyInfo = Array.isArray(googleData?.dailyInfo) ? googleData.dailyInfo : [];
  if (dailyInfo.length === 0) return null;

  const hourly = {
    time: [],
    tree_pollen: [],
    alder_pollen: [],
    birch_pollen: [],
    olive_pollen: [],
    grass_pollen: [],
    weed_pollen: [],
    mugwort_pollen: [],
    ragweed_pollen: [],
  };

  let current = null;
  const noneDisplayHourly = [];

  for (const day of dailyInfo.slice(0, 5)) {
    const date = day.date
      ? [day.date.year, String(day.date.month).padStart(2, '0'), String(day.date.day).padStart(2, '0')].join('-')
      : new Date().toISOString().split('T')[0];
    const categoryValues = { tree: null, grass: null, weed: null };
    const noneDisplayFields = {};

    for (const info of (day.pollenTypeInfo || [])) {
      const field = typeCodeToAppField(getGooglePollenTypeCode(info));
      if (!field) continue;
      if (field === 'weed' && googleInfoIsPresentWithoutIndex(info)) {
        noneDisplayFields.weed_pollen = true;
      }
      if (!googleInfoHasUsableIndex(info)) continue;
      const value = googleIndexToPollenValue(info.indexInfo.value);
      if (hasNumericValue(value)) {
        categoryValues[field] = categoryValues[field] === null ? value : Math.max(categoryValues[field], value);
      }
    }

    const plantValues = {
      alder_pollen: null,
      birch_pollen: null,
      olive_pollen: null,
      grass_pollen: null,
      weed_pollen: null,
      mugwort_pollen: null,
      ragweed_pollen: null,
    };

    for (const info of (day.plantInfo || [])) {
      const field = plantCodeToAppField(getGooglePlantCode(info));
      if (!field) continue;
      if ((field === 'weed_pollen' || field === 'ragweed_pollen') && googleInfoIsPresentWithoutIndex(info)) {
        noneDisplayFields[field] = true;
      }
      if (!googleInfoHasUsableIndex(info)) continue;
      const value = googleIndexToPollenValue(info.indexInfo.value);
      if (hasNumericValue(value)) {
        plantValues[field] = plantValues[field] === null ? value : Math.max(plantValues[field], value);
      }
    }

    plantValues.weed_pollen = categoryValues.weed;

    const normalizedDay = {
      tree_pollen: categoryValues.tree,
      alder_pollen: plantValues.alder_pollen,
      birch_pollen: plantValues.birch_pollen,
      olive_pollen: plantValues.olive_pollen,
      grass_pollen: plantValues.grass_pollen ?? categoryValues.grass,
      weed_pollen: plantValues.weed_pollen,
      mugwort_pollen: plantValues.mugwort_pollen,
      ragweed_pollen: plantValues.ragweed_pollen,
    };

    for (const field of Object.keys(noneDisplayFields)) {
      if (hasNumericValue(normalizedDay[field])) {
        delete noneDisplayFields[field];
      }
    }

    if (!current) {
      current = {
        us_aqi: null,
        pm10: null,
        pm2_5: null,
        ozone: null,
        nitrogen_dioxide: null,
        sulphur_dioxide: null,
        carbon_monoxide: null,
        ...normalizedDay,
      };
    }
    noneDisplayHourly.push(noneDisplayFields);

    hourly.time.push(date + 'T12:00');
    for (const field of Object.keys(hourly)) {
      if (field === 'time') continue;
      hourly[field].push(normalizedDay[field] ?? null);
    }
  }

  return {
    latitude: googleData.regionCode ? undefined : googleData.latitude,
    longitude: googleData.longitude,
    current,
    hourly,
    pollen_null_display_as_none: {
      current: noneDisplayHourly[0] || {},
      hourly: noneDisplayHourly,
    },
    pollen_source: 'google',
    pollen_units: 'Google index scaled to app pollen value range',
  };
}

function tomorrowIndexToPollenValue(indexValue) {
  // Tomorrow.io pollen indexes are ordinal values (0-5). Keep the same scaling
  // used for Google so mixed-source payloads stay in the app's expected range.
  if (!hasNumericValue(indexValue)) return null;
  return Math.max(0, Number(indexValue)) * 50;
}

function normalizeTomorrowPollen(tomorrowData) {
  const intervals = Array.isArray(tomorrowData?.data?.timelines?.[0]?.intervals)
    ? tomorrowData.data.timelines[0].intervals
    : Array.isArray(tomorrowData?.timelines?.daily)
      ? tomorrowData.timelines.daily.map(day => ({ startTime: day.time, values: day.values }))
      : [];
  if (intervals.length === 0) return null;

  const hourly = {
    time: [],
    tree_pollen: [],
    alder_pollen: [],
    birch_pollen: [],
    olive_pollen: [],
    grass_pollen: [],
    weed_pollen: [],
    mugwort_pollen: [],
    ragweed_pollen: [],
  };

  let current = null;
  for (const interval of intervals.slice(0, 5)) {
    const values = interval.values || {};
    const normalizedDay = {
      tree_pollen: null,
      alder_pollen: null,
      birch_pollen: null,
      olive_pollen: null,
      grass_pollen: tomorrowIndexToPollenValue(values.grassIndex),
      weed_pollen: tomorrowIndexToPollenValue(values.weedIndex),
      mugwort_pollen: null,
      ragweed_pollen: null,
    };

    if (!current) {
      current = {
        us_aqi: null,
        pm10: null,
        pm2_5: null,
        ozone: null,
        nitrogen_dioxide: null,
        sulphur_dioxide: null,
        carbon_monoxide: null,
        ...normalizedDay,
      };
    }

    hourly.time.push(interval.startTime || new Date().toISOString());
    for (const field of Object.keys(hourly)) {
      if (field === 'time') continue;
      hourly[field].push(normalizedDay[field] ?? null);
    }
  }

  return {
    current,
    hourly,
    pollen_source: 'tomorrow',
    pollen_units: 'Tomorrow.io index scaled to app pollen value range',
  };
}




function asJsDate(value) {
  if (value instanceof Date) return value;
  if (typeof value === 'number' && Number.isFinite(value)) return new Date(value);
  const parsed = new Date(value);
  return Number.isFinite(parsed.getTime()) ? parsed : new Date();
}

function pollenEmoji(level) {
  switch (level) {
    case 0: return '😊';
    case 1: return '🙂';
    case 2: return '😐';
    case 3: return '😷';
    case 4: return '🤧';
    default: return '🌿';
  }
}

function circularMeanDegrees(values) {
  let sinSum = 0;
  let cosSum = 0;
  let count = 0;
  for (const value of values) {
    if (!Number.isFinite(value)) continue;
    const rad = value * Math.PI / 180;
    sinSum += Math.sin(rad);
    cosSum += Math.cos(rad);
    count++;
  }
  if (!count) return null;
  let deg = Math.atan2(sinSum, cosSum) * 180 / Math.PI;
  if (deg < 0) deg += 360;
  return deg;
}

// Member keys look like wind_direction_10m_icon_seamless_member01.
// Reject longer variable names that share the prefix (cloud_cover vs cloud_cover_low).
function ensembleMemberSeries(container, variable) {
  if (!container || !variable) return [];
  const blocked = {
    cloud_cover: ['low', 'mid', 'high'],
    wind_direction_10m: ['dominant'],
    wind_gusts_10m: ['max'],
    wind_speed_10m: ['max']
  }[variable] || [];
  const prefix = variable + '_';
  const series = [];
  for (const key of Object.keys(container)) {
    if (key !== variable && !key.startsWith(prefix)) continue;
    const tail = key === variable ? '' : key.slice(prefix.length);
    if (blocked.some((word) => tail === word || tail.startsWith(word + '_'))) continue;
    const value = container[key];
    if (Array.isArray(value)) series.push(value);
  }
  return series;
}

function aggregateMemberHours(seriesList, length, reducer) {
  if (!seriesList.length || !length) return null;
  const result = new Array(length).fill(null);
  let any = false;
  for (let i = 0; i < length; i++) {
    const values = [];
    for (const series of seriesList) {
      const value = series[i];
      if (Number.isFinite(value)) values.push(value);
    }
    if (!values.length) continue;
    result[i] = reducer(values);
    any = true;
  }
  return any ? result : null;
}

function roundSeries(series, decimals) {
  if (!series) return series;
  const factor = 10 ** decimals;
  return series.map((value) => Number.isFinite(value) ? Math.round(value * factor) / factor : value);
}

function attachNativeWindAndCloud(raw, n) {
  if (!n || !n.hourly) return;
  const hourly = raw && raw.hourly;
  const len = Array.isArray(n.hourly.time) ? n.hourly.time.length : 0;
  const gusts = aggregateMemberHours(ensembleMemberSeries(hourly, 'wind_gusts_10m'), len, averageEnsembleValues);
  const dirs = aggregateMemberHours(ensembleMemberSeries(hourly, 'wind_direction_10m'), len, circularMeanDegrees);
  if (gusts) n.hourly.wind_gusts_10m = roundSeries(gusts, 1);
  if (dirs) {
    n.hourly.wind_direction_10m = roundSeries(dirs, 0).map((value) => value === 360 ? 0 : value);
  }
  for (const name of ['cloud_cover_low', 'cloud_cover_mid', 'cloud_cover_high']) {
    if (Array.isArray(n.hourly[name]) && n.hourly[name].some((value) => Number.isFinite(value))) continue;
    const avg = aggregateMemberHours(ensembleMemberSeries(hourly, name), len, averageEnsembleValues);
    if (avg) n.hourly[name] = roundSeries(avg, 1);
  }
}

function normalizeEnsembleForNative(raw, lat, lon) {
  const n = normalizeEnsembleWeatherData(raw, lat, lon);
  attachNativeWindAndCloud(raw, n);
  const idx = nearestTimeIndex(n.hourly && n.hourly.time ? n.hourly.time : [], new Date());
  if (n.current && n.hourly) {
    if (n.hourly.is_day) n.current.is_day = n.hourly.is_day[idx];
    if (n.hourly.precipitation) n.current.precipitation = n.hourly.precipitation[idx];
    if (n.hourly.cloud_cover) n.current.cloud_cover = n.hourly.cloud_cover[idx];
    if (n.hourly.wind_direction_10m) n.current.wind_direction_10m = n.hourly.wind_direction_10m[idx];
    if (n.hourly.wind_gusts_10m) n.current.wind_gusts_10m = n.hourly.wind_gusts_10m[idx];
  }
  return n;
}

function moonTimesMs(ms, lat, lon) {
  const r = calculateMoonRiseSet(asJsDate(ms), lat, lon);
  return {
    rise: r.rise instanceof Date ? r.rise.getTime() : null,
    set: r.set instanceof Date ? r.set.getTime() : null,
    alwaysUp: !!r.alwaysUp,
    alwaysDown: !!r.alwaysDown
  };
}

function nextMoonMs(kind, ms) {
  const fn = kind === 'full' ? getNextFullMoon : getNextNewMoon;
  const r = fn(asJsDate(ms));
  return { ms: r.date instanceof Date ? r.date.getTime() : null, days: r.days };
}

function nearestTimeIndexMs(times, ms) {
  return nearestTimeIndex(times, asJsDate(ms));
}

function buildPollenForecastDays(aqiData) {
  const hourlyData = aqiData && aqiData.hourly;
  if (!hourlyData || !Array.isArray(hourlyData.time)) return [];
  const dailyData = {};
  for (let i = 0; i < hourlyData.time.length; i++) {
    const date = String(hourlyData.time[i]).split('T')[0];
    if (!dailyData[date]) {
      dailyData[date] = { date: date, tree: null, grass: null, weed: null, weedNullDisplayAsNone: false };
    }
    dailyData[date].weedNullDisplayAsNone = dailyData[date].weedNullDisplayAsNone || shouldDisplayNullPollenAsNone(aqiData, ['weed_pollen', 'mugwort_pollen', 'ragweed_pollen'], i);
    dailyData[date].tree = maxAvailablePollen([
      dailyData[date].tree,
      hourlyData.tree_pollen && hourlyData.tree_pollen[i],
      hourlyData.alder_pollen && hourlyData.alder_pollen[i],
      hourlyData.birch_pollen && hourlyData.birch_pollen[i],
      hourlyData.olive_pollen && hourlyData.olive_pollen[i]
    ]);
    dailyData[date].grass = maxAvailablePollen([
      dailyData[date].grass,
      hourlyData.grass_pollen && hourlyData.grass_pollen[i]
    ]);
    dailyData[date].weed = maxAvailablePollen([
      dailyData[date].weed,
      hourlyData.weed_pollen && hourlyData.weed_pollen[i],
      hourlyData.mugwort_pollen && hourlyData.mugwort_pollen[i],
      hourlyData.ragweed_pollen && hourlyData.ragweed_pollen[i]
    ]);
  }
  return Object.keys(dailyData).slice(0, 5).map(function (dateStr, index) {
    const data = dailyData[dateStr];
    const treeLevel = getPollenLevel(data.tree);
    const grassLevel = getPollenLevel(data.grass);
    const weedLevel = getPollenLevel(data.weed, { displayNullAsNone: data.weedNullDisplayAsNone });
    const overall = Math.max(treeLevel.level || 0, grassLevel.level || 0, weedLevel.level || 0);
    return {
      date: dateStr,
      index: index,
      tree: data.tree,
      grass: data.grass,
      weed: data.weed,
      treeLabel: treeLevel.label,
      grassLabel: grassLevel.label,
      weedLabel: weedLevel.label,
      emoji: pollenEmoji(overall)
    };
  });
}



var JaccuweatherLogic = {
  normalizeEnsembleWeatherData: normalizeEnsembleWeatherData,
  normalizeEnsembleForNative: normalizeEnsembleForNative,
  getWeatherIconFile: getWeatherIconFile,
  getWeatherDescription: getWeatherDescription,
  getAlertIconFile: getAlertIconFile,
  calculateMoonPhase: function (ms) { return calculateMoonPhase(asJsDate(ms)); },
  getMoonPhase: getMoonPhase,
  getMoonIllumination: function (ms) { return getMoonIllumination(asJsDate(ms)); },
  calculateMoonDistance: function (ms, lat, lon) { return calculateMoonDistance(asJsDate(ms), lat, lon); },
  calculateMoonRiseSet: calculateMoonRiseSet,
  moonTimesMs: moonTimesMs,
  getNextFullMoon: function (ms) { return nextMoonMs('full', ms); },
  getNextNewMoon: function (ms) { return nextMoonMs('new', ms); },
  formatIsoLocalClock: formatIsoLocalClock,
  formatInstantInLocation: formatInstantInLocation,
  formatTime12Hour: formatTime12Hour,
  formatLastUpdatedBetween: formatLastUpdatedBetween,
  shouldRefetchStaleForecast: shouldRefetchStaleForecast,
  parseLocationLocalIso: parseLocationLocalIso,
  nearestTimeIndex: nearestTimeIndexMs,
  hpaToInhg: hpaToInhg,
  calculateDailyAveragesForDateString: calculateDailyAveragesForDateString,
  getAverageHourlyValueForDate: getAverageHourlyValueForDate,
  calculateSinusRisk: calculateSinusRisk,
  getPressureTrend: getPressureTrend,
  getSinusDrivers: getSinusDrivers,
  getSimpleRiskLabel: getSimpleRiskLabel,
  calculateAllergyRisk: calculateAllergyRisk,
  getAllergyDrivers: getAllergyDrivers,
  getNiceWeatherBreakdown: getNiceWeatherBreakdown,
  getNiceWeatherLabel: getNiceWeatherLabel,
  getPollenLevel: getPollenLevel,
  maxAvailablePollen: maxAvailablePollen,
  hasAnyPollenData: hasAnyPollenData,
  formatPollenValue: formatPollenValue,
  shouldDisplayNullPollenAsNone: shouldDisplayNullPollenAsNone,
  buildPollenForecastDays: buildPollenForecastDays,
  uvCategoryLabel: uvCategoryLabel,
  maxHourlyUvForDateString: maxHourlyUvForDateString,
  normalizeGooglePollen: normalizeGooglePollen,
  normalizeTomorrowPollen: normalizeTomorrowPollen,
  hasAnyUsablePollen: hasAnyUsablePollen,
  haversineKm: haversineKm,
  normalizeNoaaStations: normalizeNoaaStations,
  interpolateTideCurve: interpolateTideCurve,
  buildTideDailySummaries: buildTideDailySummaries,
  parseNoaaPredictionRow: parseNoaaPredictionRow,
  isLikelyUsLocation: isLikelyUsLocation,
  extractDurationHours: extractDurationHours,
  overlapHours: overlapHours,
  HOURLY_FORECAST_HOURS: HOURLY_FORECAST_HOURS,
  STALE_REFETCH_AFTER_MS: STALE_REFETCH_AFTER_MS
};
if (typeof module !== 'undefined' && module.exports) module.exports = JaccuweatherLogic;
